name: Update Azure VM

on:
  schedule:
    - cron: '0 6 * * *'

jobs:
  update-vm:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Run SSH command to update VM
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.AZURE_VM_HOST }}
        username: ${{ secrets.AZURE_VM_USERNAME }}
        key: ${{ secrets.AZURE_VM_SSH_KEY }}
        script: |
          cd /home/azureuser/Haidi-server
          sudo docker compose down
          git pull origin main
          sudo docker-compose up --build -d